---

avi_servers_ips:
  - 100.64.129.203
  - 100.64.129.204

avi_servers_port: 80

avi_cloud:
  name: Default-Cloud

domain_name: vcenter.avi.com

network_name: vxw-dvs-34-virtualwire-120-sid-6120119-wdc-06-vc12-avi-dev116

tenant_ref: admin

avi_healthmonitor:
  - name: &hm ansible-hm1
    receive_timeout: 1
    failed_checks: 2
    send_interval: 1
    successful_checks: 2
    type: HEALTH_MONITOR_HTTP
    http_request: "HEAD / HTTP/1.0"
    http_response_code:
      - HTTP_2XX
      - HTTP_3XX
      - HTTP_5XX

avi_pool:
  name: &pool ansible-pool1
  health_monitor_refs: *hm

avi_virtualservice:
  http:
    - name: &vs0 ansible-app1
      services:
        - port: 80
          enable_ssl: false
        - port: 443
          enable_ssl: true
      pool_ref: *pool
      enable_rhi: false
      se_group_ref: Default-Group